spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatisdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
pagehelper:
  helper-dialect: mysql
  reasonable: true
server:
  port: 8088